import Link from "next/link";
import Image from "next/image";

import Head from 'next/head'

export default function FaleConosco() {
    return (
        <>
            <Head>
                <title>MOCAP&trade; - Fale Conosco</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}