import Link from 'next/link'
import Image from 'next/image'

import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>MOCAP&trade; - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className='home-container'>
        <div>

          {/* tittle ================================================================================================== */}

          <div class="text-box">
            <h1>de qualidade</h1>
            <h1>de qualidade</h1>
          </div>

          <button className="fancy">
            <span className="top-key"></span>
            <Link href={{pathname: "/portfolio"}}>Portifólio</Link>
            <span className="bottom-key-1"></span>
            <span className="bottom-key-2"></span>
          </button>
        </div>
      </section>
    </>
  )
}
